apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-app1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app1
  namespace: my-nginx-app1
  labels:
    name: nginx-app1
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-app1
  template:
    metadata:
      namespace: my-nginx-app1
      labels:
        name: nginx-app1
    spec:
      containers:
      - name: nginx-app1
        image: nginx
        ports:
        - containerPort: 80

