apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-app2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app2
  namespace: my-nginx-app2
  labels:
    name: nginx-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-app2
  template:
    metadata:
      namespace: my-nginx-app2
      labels:
        name: nginx-app2
    spec:
      containers:
      - name: nginx-app2
        image: nginx
        ports:
        - containerPort: 80

