---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app1
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./app1
  prune: true
  sourceRef:
    kind: GitRepository
    name: app1

